
/* generated by: ControllerGenerator Wed May 18 15:20:45 CEST 2016 */
package com.littleworld.todo.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Todo {
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  int id;
  String firstName;
  String lastName;
  String userName;
  String passWord;
  String place;

  public Todo() {}

  public Todo(int id, String firstName, String lastName, String userName, String passWord, String place) {
    this.id = id;
    this.firstName = firstName;
    this.lastName = lastName;
    this.userName = userName;
    this.passWord = passWord;
    this.place = place;
  }

  public int getId() { return id; }
  public void setId(int id)  { this.id = id; }

  public String getFirstName() { return firstName; }
  public void setFirstName(String firstName) { this.firstName = firstName; }

  public String getLastName() { return lastName; }
  public void setLastName(String lastName) { this.firstName = lastName; }

  public String getUserName() { return userName; }
  public void setUserName(String userName)  { this.userName = userName; }

  public String getPassWord() {
    return passWord;
  }
  public void setPassWord(String passWord) {
    this.passWord = passWord;
  }

  public String getPlace() { return place; }
  public void setPlace(String place) { this.place = place; }

}

