
/* generated by: ControllerGenerator Wed May 18 15:20:45 CEST 2016 */
package com.littleworld.todo.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Todo {
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  int id;

  String userName;
  String passWord;

  public Todo() {}

  public Todo(int id, String task, String passWord) {
    this.id = id;
    this.userName = task;
    this.passWord = passWord;
  }

  public int getId() { return id; }
  public void setId(int id)  { this.id = id; } 
  public String getUserName() { return userName; }
  public void setUserName(String task)  { this.userName = task; }

  public String getPassWord() {
    return passWord;
  }

  public void setPassWord(String passWord) {
    this.passWord = passWord;
  }

  @Override
  public String toString() {
    return "[Todo: [" + "id: " + id + ", " + "task: " + userName + "]"; 
  }
}

